name: Get infrastructure flow environment
description: |-
  Composite action to mutualize the logic of getting Github environment on both plan and deploy situations

# TODO: can be simplify to a single output: 'environment'
outputs:
  deploy_environment: 
      description: infrastructure deployment associated environment
      value: ${{ steps.get_deploy_env.outputs.environment }}
  plan_environment: 
      description: infrastructure plan associated environment
      value: ${{ steps.get_plan_env.outputs.environment }}


# TODO: can be simplify with a single step with no trigger condition. Condition is up to the caller of this composite action
runs:
    using: composite
    steps:
        # TODO: as a rule of thumb, a composite action should not contain conditions. Up to the caller to implement itself the condition logic to call or not the composite action
        - if: github.event_name == 'push' && contains(fromJSON('["integration", "staging", "production"]'), github.ref_name) 
          name: get infrastructure deployment env
          id: get_deploy_env
          shell: bash
          run: |- 
            if [ ${{ github.ref_name }} = "integration" ]; then
                echo "integration"
                echo 'environment=integration' >> "$GITHUB_OUTPUT"
            elif [ ${{ github.ref_name }} = "staging" ]; then
                echo "staging"
                echo 'environment=staging' >> "$GITHUB_OUTPUT"
            elif [[ ${{ github.ref_name }} = "production" ]]; then
                echo "production"
                echo 'environment=production' >> "$GITHUB_OUTPUT"
            else
                exit 1
            fi

        - if: github.event_name == 'pull_request' 
          name: get infrastructure plan environment
          id: get_plan_env
          shell: bash
          run: |- 
            if [ "${{ github.base_ref }}" = "integration" ]; then
                echo "integration"
                echo 'environment=integration' >> "$GITHUB_OUTPUT"
            elif [ "${{ github.base_ref }}" = "staging" ]; then
                echo "staging"
                echo 'environment=staging' >> "$GITHUB_OUTPUT"
            elif [[ "${{ github.base_ref }}" = "production" ]]; then
                echo "production"
                echo 'environment=production' >> "$GITHUB_OUTPUT"
            else
                exit 1
            fi