# Cannot work since composite actions cannot acces the 'vars' context --> TODO: to confirm.
# https://github.com/orgs/community/discussions/51280
name: Get workload flow environment
description: |-
  Composite action to mutualize the logic of getting Github environment 

inputs:
  environment:
    description: Github action environment name
    required: true

outputs:
  project_id: 
      description: associated workflow environment
      value: ${{ steps.guess_env.outputs.environment }}
  repository_id: 
      description: associated workflow environment
      value: ${{ steps.guess_env.outputs.environment }}
  workload_identity_provider: 
      description: associated workflow environment
      value: ${{ steps.guess_env.outputs.environment }}
  service_account_to_impersonate: 
      description: associated workflow environment
      value: ${{ steps.guess_env.outputs.environment }}
  region: 
      description: associated workflow environment
      value: ${{ steps.guess_env.outputs.environment }}


runs:     
    using: composite
    steps:
        - name: Getting project id
          shell: bash
          id: get_project_id
          run: |-
            echo "${{ vars.PROJECT_ID }}"
            echo "project_id=${{ vars.PROJECT_ID }}" >> "$GITHUB_OUTPUT"

        - name: Getting repository id
          shell: bash
          id: get_repository_id
          run: |-
            echo "${{ vars.REPOSITORY_ID }}"
            echo "repository_id=${{ vars.REPOSITORY_ID }}" >> "$GITHUB_OUTPUT"

        - name: Getting workload identity provider
          shell: bash
          id: get_workload_identity_provider
          run: |-
            echo "${{ vars.WORKLOAD_IDENTITY_PROVIDER }}"
            echo "workload_identity_provider=${{ vars.WORKLOAD_IDENTITY_PROVIDER }}" >> "$GITHUB_OUTPUT"

        - name: Getting service account to impersonate
          shell: bash
          id: get_sa_to_impersonate
          run: |-
            echo "${{ vars.SA_TO_IMPERSONATE }}"
            echo "service_account_to_impersonate=${{ vars.SA_TO_IMPERSONATE }}" >> "$GITHUB_OUTPUT"
            
        - name: Getting region
          shell: bash
          id: get_region
          run: |-
            echo "${{ vars.CLOUD_REGION }}"
            echo "region=${{ vars.CLOUD_REGION }}" >> "$GITHUB_OUTPUT"