#TODO: maybe to remove since already taken into account by release-action
name: Tag branches
description: |-
  Return list of images in a given artifact repository

inputs:
  project_id:
    description: id of the project entity hosting package repository
    required: true 
  repository_id:
    description: Image repository id
    required: true
  workload_identity_provider:
    description: Identifier of the concrete workload identity provider.
    required: true
  service_account_to_impersonate:
    description: Identity to impersonate through the workload identity provider
    required: true
  region:
    description: Region of the concrete artifactory service
    required: true

runs:
        # We need both
        # https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28#create-a-tag-object
        # https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28#create-a-tag-object
        # usage: https://stackoverflow.com/questions/60963759/use-github-actions-to-create-a-tag-but-not-a-release
      using: composite
      steps:
        - name: create tag at the git level
          id: create git tag
          shell: bash
          run: |-
            echo "create git tag"

        - name: create tag at the github level
          id: create github tag
          shell: bash
          run: |-
            echo "create github tag"

      
