name: Infrastructure integration and deployment
run-name: '${{ github.actor }} triggered Infrastructure workflow'

on:
    push:
        paths: 
            - infrastructure/**.tf
            - infrastructure/CHANGELOG.md
    pull_request: 
        branches:
            - main
        paths: 
            - infrastructure/**.tf

jobs:

    infrastructure_integration:
        uses: ./.github/workflows/infrastructure_integration.yaml


    check_infrastructure_source_changes:
        if: github.event_name == 'pull_request' || github.ref_name == 'main'
        needs: infrastructure_integration
        uses: ./.github/workflows/_check_source_changes.yaml
        with:
          files: |
            **/*.tf
          get_folders: true


    infrastructure_plan:
        # if: needs.check_infrastructure_source_changes.outputs.is_modified_files && (github.event_name == 'pull_request' || github.ref_name == 'main') 
        if: false
        needs: check_infrastructure_source_changes
        uses: ./.github/workflows/infrastructure_plan.yaml
        permissions: 
            pull-requests: write
            contents: read
            id-token: write
        strategy:
            fail-fast: false
            matrix:
              root_module_path: ${{ fromJSON(needs.check_infrastructure_source_changes.outputs.all_changed_files) }}
        with:
            root_module_path : ${{ matrix.root_module_path }}


    release: 
        if: github.ref_name == 'main'
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-22.04
        steps:

            - uses: googleapis/release-please-action@v4
              id: release
              with:
                token: ${{ github.token }}

            - uses: actions/checkout@v4
  
            - name: tag major and minor versions
              if: ${{ steps.release.outputs.infrastructure--release_created }}
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
                  git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/googleapis/release-please-action.git"
                  git tag -d v${{ steps.release.outputs.infrastructure--major }} || true
                  git tag -d v${{ steps.release.outputs.infrastructure--major }}.${{ steps.release.outputs.infrastructure--minor }} || true
                  git push origin :v${{ steps.release.outputs.infrastructure--major }} || true
                  git push origin :v${{ steps.release.outputs.infrastructure--major }}.${{ steps.release.outputs.infrastructure--minor }} || true
                  git tag -a v${{ steps.release.outputs.infrastructure--major }} -m "Release v${{ steps.release.outputs.infrastructure--major }}"
                  git tag -a v${{ steps.release.outputs.infrastructure--major }}.${{ steps.release.outputs.infrastructure--minor }} -m "Release v${{ steps.release.outputs.infrastructure--major }}.${{ steps.release.outputs.infrastructure--minor }}"
                  git push origin v${{ steps.release.outputs.infrastructure--major }}
                  git push origin v${{ steps.release.outputs.infrastructure--major }}.${{ steps.release.outputs.infrastructure--minor }}
