name: Infrastructure integration and deployment
run-name: '${{ github.actor }} triggered Infrastructure workflow'

on:
    push:
        paths: 
            - infrastructure/**.tf
        branches-ignore: 
            - main
    pull_request: 
        branches:
            - main
        paths: 
            - infrastructure/**.tf

jobs:

    infrastructure_integration:
        uses: ./.github/workflows/infrastructure_integration.yaml


    check_infrastructure_source_changes:
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        needs: infrastructure_integration
        uses: ./.github/workflows/_check_source_changes.yaml
        with:
          files: |
            **/*.tf
          get_folders: true


    infrastructure_plan:
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        needs: check_infrastructure_source_changes
        uses: ./.github/workflows/infrastructure_plan.yaml
        permissions: 
            pull-requests: write
            contents: read
            id-token: write
        strategy:
            fail-fast: false
            matrix:
              root_module_path: ${{ fromJSON(needs.check_infrastructure_source_changes.outputs.all_changed_files) }}
        with:
            root_module_path : ${{ matrix.root_module_path }}

    # TODO: if pull request, push the content of plan workflow output in the PR comment