name: Deploy workloads releases
run-name: '${{ github.actor }} triggers workload deployment for environment ${{ github.action_ref }}'
 
# TODO: to document: # whatever happens, we deploy on the current sha1
# to document: service name take the name of the folder containing "Dockerfile". It's a contract we have with the infrastructure. Cloud run service must already exists.
# Same thing with the job. They must exist and their name is on the "Dockerfile_[job_name]" itself

on: 
  workflow_dispatch: 
    inputs:
        environment:
            description: On what environment to deploy the targeted version
            options:
                - integration
                - staging
                - production
            type: choice
            required: true
            default: integration
        

jobs:


    get_images_common_tag:
      runs-on: ubuntu-22.04
      outputs:
        common_tag_to_deploy: ${{ steps.common_tag.outputs.common_tag_to_deploy }}
      steps:
        - name: Validate the triggering reference is of tag type
          id: check_ref_type
          run: |-
            if [ ${{ github.ref_type }} = branch ]; then
              echo "You cannot deploy with a branch as reference type. Please choose a release tag"
              exit 1
            fi

        - name: Get common tag for deployment
          id: common_tag
          run: |-
            common_tag_to_deploy=${{ github.ref_name }} 
            echo "common tag to deploy: ${common_tag_to_deploy}"
            echo "common_tag_to_deploy=${common_tag_to_deploy}" >> $GITHUB_OUTPUT
    

    expose_vars:
      runs-on: ubuntu-22.04
      environment: ${{ inputs.environment }}
      outputs:
        PROJECT_ID: ${{ vars.PROJECT_ID }}
        REPOSITORY_ID: ${{ vars.REPOSITORY_ID }}
        WORKLOAD_IDENTITY_PROVIDER: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
        SA_TO_IMPERSONATE: ${{ vars.SA_TO_IMPERSONATE }}
        CLOUD_REGION: ${{ vars.CLOUD_REGION }}
      steps:
        - name: Exposing env vars
          run: echo "Exposing env vars"

    workloads_deployment:
      needs: [expose_vars, get_images_common_tag]
      uses: ./.github/workflows/workload_deployment.yaml
      with:
          environment: ${{ inputs.environment }}
          workload_identity_provider: ${{ needs.expose_vars.outputs.WORKLOAD_IDENTITY_PROVIDER }}
          service_account_to_impersonate: ${{ needs.expose_vars.outputs.SA_TO_IMPERSONATE }}
          cloud_region: ${{ needs.expose_vars.outputs.CLOUD_REGION }}
          project_id: ${{ needs.expose_vars.outputs.PROJECT_ID }}
          repository_id: ${{ needs.expose_vars.outputs.REPOSITORY_ID }}
          tag: ${{ needs.get_images_common_tag.outputs.common_tag_to_deploy }}
