name: Cloud Run service deployment
run-name: '${{ github.event_name }} needs to look for source changes'


on:
    workflow_call: 
        inputs:
            service_name:
                description: Cloud Run service name to deploy
                type: string
                required: true
            image:
                description: fully qualified name of the image associated to the service
                type: string
                required: true

jobs:
    deploy_service:
        runs-on: ubuntu-22.04
        steps:
            - name: todo
              run: |-
                echo "TODO" #https://github.com/google-github-actions/deploy-cloudrun
            