name: reusable workflow
run-name: ${{ github.actor }} define reusable workflow 

on:
    workflow_call:
      inputs:
        config-path:
          required: false
          type: string
      secrets:
        token:
          required: false
      outputs:
        message:
            description: "reusable workflow output from job1: msg1"
            value: ${{ jobs.job1.outputs.msg }}
        message2:
            description: "reusable workflow output from job1: msg2"
            value: ${{ jobs.job1.outputs.msg2 }}
        message3:
            description: "reusable workflow output from job3: msg"
            value: ${{ jobs.job2.outputs.msg3 }}
  
jobs:
    job1:
        name: generate output
        runs-on: ubuntu-latest
        outputs:
            msg: ${{ steps.step1.outputs.msg }}
            msg2: ${{ steps.step2.outputs.msg2 }}
        steps:
          - run: echo "msg=Hello world" >> "$GITHUB_OUTPUT"
            id: step1
          - id: step2
            run: echo "msg2=Foo bar" >> "$GITHUB_OUTPUT"
          - id: step3
            run: echo "foo"
          - id: step4
            run: echo "bar"
    job2:
        name: Capitalize job output 1
        runs-on: ubuntu-latest
        needs: [job1]
        outputs:
          msg3: ${{ steps.step1.outputs.msg }}
        steps:
          - run: echo "msg=${{ needs.job1.outputs.msg }}_to_capital" >> "$GITHUB_OUTPUT"
            id: step1
        