name: Backend integration
run-name: '${{ github.actor }} triggers backend integration'

on:
    push: 
        branches-ignore: 
            - main
            - release
            - release/**
        paths: 
            - application/backend/**
    workflow_call: 

jobs:
    check-source-changes:
      uses: ./.github/workflows/_check_source_changes.yaml
      with:
        files: |
          application/backend/**
        files_ignore: |
          application/backend/*.md
          application/backend/Dockerfile*
          application/backend/.dockerignore

    nest_application_integration:
      needs: check-source-changes
      if: needs.check-source-changes.outputs.is_modified_files == 'true'
      uses: ./.github/workflows/_nestjs_integration.yaml
      with:
        application_folder_path: './backend'
      
