name: "Frontend continuous integration"

run-name: "${{ github.actor }} triggers Frontend continuous integration"

on:
    push: 
        branches-ignore: 
            - main
            - release
            - release/**
        paths: 
            - frontend/**

jobs:
    next-application-integration:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Get changed file
              id: changed-files
              uses: tj-actions/changed-files@v44
              with:
                files_ignore: |
                    "**/*.md"
                    "**/*Dockerfile"
                    "**/*.dockerignore"
            - name: List all changed files
              env:
                ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
              run: |
                for file in ${ALL_CHANGED_FILES}; do
                  echo "$file was changed"
                done
        
              