name: "Frontend continuous integration"

run-name: "${{ github.actor }} triggers Frontend continuous integration"

on:
    push: 
        branches-ignore: 
            - main
            - release
            - release/**
        paths: 
            - frontend/**

jobs:
    check-sources-change:
        runs-on: ubuntu-22.04
        outputs:
          launch_integration_job: ${{ steps.sources_modified.outputs.output }}
        steps:
            - uses: actions/checkout@v4
            
            - name: Get changed file
              id: changed-files
              uses: tj-actions/changed-files@v44
              with:
                files: |
                  frontend/**
                files_ignore: |
                  frontend/*.md
                  frontend/Dockerfile
                  frontend/.dockerignore

            - name: Are sources modified
              id: sources_modified
              run: | 
                echo ${{ steps.changed-files.outputs.all_modified_files_count }}
                echo "output=${{ steps.changed-files.outputs.all_modified_files_count > 0 }}" >> "$GITHUB_OUTPUT"

    next_application_integration:
      needs: check-sources-change
      runs-on: ubuntu-22.04
      if: ${{ needs.check-sources-change.outputs.launch_integration_job == 'true' }}
      steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: test
          id: test
          run: echo "Hello world"

        - name: launch integration
          id: integration
          uses: ./.github/workflows/_nextjs_integration.yaml
