name: "Frontend continuous integration"

run-name: "${{ github.actor }} triggers Frontend continuous integration"

on:
    push: 
        # branches-ignore: 
        #     - main
        #     - release
        #     - release/**
        # paths: 
        #     - frontend/**

jobs:
    check-sources-change:
      uses: ./.github/workflows/_check_source_changes.yaml
      with:
        files: |
          backend/**
        files_ignore: |
          backend/*.md
          backend/Dockerfile
          backend/.dockerignore

    next_application_integration:
      needs: check-sources-change
      if: ${{ needs.check-sources-change.outputs.launch_integration_job == 'true' }}
      uses: ./.github/workflows/_nextjs_integration.yaml
      with:
        application_folder_path: "./frontend"
      
