name: Infrastructure integration
run-name: '${{ github.actor }} triggers infrastructure integration'

on:
    push: 
        branches-ignore: 
            - main
            - integration
            - staging
            - production
        paths: 
            - infrastructure/**
    workflow_call:
      inputs:
        terraform_version:
          description: Terraform version to install
          type: string
          required: false
          default: '1.9.0'

jobs:
    
    check_source_changes:
      uses: ./.github/workflows/_check_source_changes.yaml
      with:
        files: |
          **/*.tf
        get_folders: true

        
    infrastructure_integration:
      needs: check_source_changes
      if: needs.check_source_changes.outputs.is_modified_files == 'true'
      permissions: 
        pull-requests: write
        contents: read
        id-token: write
      uses: ./.github/workflows/_terraform_integration.yaml
      strategy:
        fail-fast: false
        matrix:
          root_module_path: ${{ fromJSON(needs.check_source_changes.outputs.all_changed_files) }}
      with:
        terraform-version: ${{ inputs.terraform_version }}
        root-module-path : ${{ matrix.root_module_path }}
          
      
        
    
        
        
      
    
          
      