name: Infrastructure deployment
run-name: '${{ github.actor }} triggers infrastructure deployment'

on:
    workflow_call:
      inputs:
        environment:
          description: Targeted environment for infrastructure deployment
          type: string
          required: true
        terraform_version:
            description: Terraform version to install
            type: string
            required: false
            default: '1.9.0' 
        root_module_path:
          description: Absolute path from the root git context to the root module to apply
          type: string
          required: true

jobs:

    infrastructure_deployment:
      permissions: 
        pull-requests: write
        contents: read
        id-token: write
      uses: ./.github/workflows/_terraform_application.yaml
      with:
        terraform-version: ${{ inputs.terraform_version }}
        root-module-path : ${{ inputs.root_module_path }}
        environment: ${{ inputs.environment }}

          
      
        
    
        
        
      
    
          
      