name: test to delete


on:
    push: 
        branches: 
            - main


jobs:
    backend_ci:
        uses: ./.github/workflows/container_cd.yaml
        with:
            files: |
                ./fontend/**
                ./backend/**
            files_ignore: |
                **/*.md