name: test
run-name: test

on:
    workflow_dispatch: 

jobs:
    cloud_run_tryout:
        environment: 
          name: integration
        runs-on: ubuntu-22.04
        permissions: 
            pull-requests: write
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4

            - name: Authenticate to gcp workload identity pool
              id: auth_to_google
              uses: 'google-github-actions/auth@v2'
              with:
                  workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
                  service_account: ${{ vars.SA_TO_IMPERSONATE }}
                  create_credentials_file: true


            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v2'
              with:
                version: '>= 363.0.0'

            - name: 'Use gcloud CLI'
              run: 'gcloud info'
  