name: Test cloud run deployment
run-name: Test cloud run deployment

on:
    push: 
      branches:
        - main

jobs:
    cloud_run_deployment:
      uses: ./.github/workflows/_cloudrun_deployment.yaml
      with:
          environment: integration
          tag: latest
          docker_file_path: ./frontend/Dockerfile
