name: Workload deployment on call
run-name: '${{ github.actor }} triggers workload deployment'
 
# TODO: to document: # whatever happens, we deploy on the current sha1
# to document: service name take the name of the folder containing "Dockerfile". It's a contract we have with the infrastructure. Cloud run service must already exists.
# Same thing with the job. They must exist and their name is on the "Dockerfile_[job_name]" itself

on: 
  workflow_call:
    inputs:
      environment:
          description: Environment where we deploy
          type: string
          required: true
      workload_identity_provider:
          description: |-
            Identifier of the concrete workload identity provider. 
          required: true
          type: string
      service_account_to_impersonate:
          description: |-
            Identity to impersonate through the workload identity provider
          required: true
          type: string
      cloud_region:
          description: |-
            Region of the concrete workload cloud hosting service
          required: true
          type: string
      project_id:
          description: id of the project entity hosting image repository
          required: true
          type: string
      repository_id:
          description: Image repository id
          required: true
          type: string
      tag:
          description: 'which tag to apply'
          type: string
          required: false
          default: latest

jobs:
    get_env_var_of_interest:
      uses: ./.github/workflows/_get_env_var_of_interest.yaml
      with:
        environment: ${{ inputs.environment }}

    get_images_common_tag:
      runs-on: ubuntu-22.04
      outputs:
        common_tag_to_deploy: ${{ steps.common_tag.outputs.common_tag_to_deploy }}
      steps:
        - name: Get common tag for deployment
          id: common_tag
          run: |-
            common_tag_to_deploy=${{ github.sha }}
            echo "common tag to deploy: ${common_tag_to_deploy}"
            echo "common_tag_to_deploy=${common_tag_to_deploy}" >> $GITHUB_OUTPUT
    
    get_docker_files:
      runs-on: ubuntu-22.04
      outputs:
        docker_files: ${{ steps.list_docker_file_path.outputs.docker_files }}
      steps:
        - uses: actions/checkout@v4

        - name: list_docker_file_path
          id: list_docker_file_path
          uses: ./.github/actions/get_docker_files

      
    workloads_deployment:
      needs: [get_docker_files, get_env_var_of_interest, get_images_common_tag]
      uses: ./.github/workflows/_cloudrun_deployment.yaml
      strategy:
          matrix:
            docker_file_path: ${{ fromJson(needs.get_docker_files.outputs.docker_files) }}
      with:
          environment: ${{ inputs.environment }} # should always be 'integration' since continuous deployment is only applied on this env. staging and production are triggered through dispatch
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account_to_impersonate: ${{ inputs.service_account_to_impersonate }} 
          cloud_region: ${{ inputs.cloud_region }}
          project_id: ${{ inputs.project_id }}
          repository_id: ${{ inputs.repository_id }}
          tag: ${{ needs.get_images_common_tag.outputs.common_tag_to_deploy }}
          docker_file_path: ${{ matrix.docker_file_path }}
