name: Docker build and push
description: |-
  Composite action to build and push docker images. Image tag is taken from the sha1 associated to the triggering event. 

inputs:
    dockerfile_path:
        description: Path of the considered dockerfile
        required: true
    image_tag:
        description: |-
          Complete image tag name
        required: true
    registry_id:
        description: |-
          Id of the Cloud artifact registry repository where image will be stored
        required: true
    access_token:
        description: |-
          Oauth2 access token used to authenticate on the artifactory.
        required: true

runs:
    using: composite
    steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4

        - name: Set up QEMU
          id: set-up-qemu
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          id: set-up-docker-buildx
          uses: docker/setup-buildx-action@v3

        - name: extract dockerfile dirname
          id: dockerfile-dirname
          shell: bash
          run: echo "dirname=$(dirname ${{ inputs.dockerfile_path }})" >> "$GITHUB_OUTPUT"

        - name: Docker Authentication
          id: docker_auth
          uses: docker/login-action@v3
          with:
              username: oauth2accesstoken
              password: ${{ inputs.access_token }}
              registry: ${{ inputs.registry_id }}

        - name: Build and push image
          id: image-build-push
          uses: docker/build-push-action@v5
          with:
              context: ./${{ steps.dockerfile-dirname.outputs.dirname }}
              file: ${{ inputs.dockerfile_path }}
              tags: ${{ inputs.image_tag }}
              push: true