# This action considers that given an image name, it either have:
# 1. a tag with the current triggering event's sha1 --> we need to allign the tag latest with this tag sha1 (creating it if not existing)
# 2. a tag 'latest' exists but no tag named after trigerring event sha1 --> We need to allign the sha1 tag with the existing 'latest' tag
# 
# We should fail if none of these situtations is true
#
# This strategy allows us to consider multi-services deploymnet with a single sha1 commit.
# Note: 
# - Tag latest is not to be referenced. Only to track the 
# - This strategy works if applied on a single branch. Generally the history source of truth for source code: default branch.
#   beware to call this action from a workflow considering a single branch only. Otherwise, latest will be relative and concurently accessed. 
# - To reset the logic, just remove tags latest from your sevice repositories

name: Gcloud Tag images
description: 'This composite action applies a tagging strategy to ensure we have the tag corresponding to trigger event_s sha1 alligned with the tag latest'

inputs:
    dockerfile-path:
        description: "Path of the considered dockerfile"
        required: true
    image_name:
        description: "Image name"
        required: true

    # artifactory id TOO

runs:
    using: "composite"
    steps:
        - id: 'auth'
          uses: 'google-github-actions/auth@v2'
          with:
            workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
            service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
    
        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v2'
    
        - name: 'Use gcloud CLI'
          shell: bash
          run: 'gcloud info'

        - name: 'Check sha1 tag existence'
          shell: bash
          run: 'gcloud info'

        - name: 'Check tag latest existence'
          shell: bash
          run: 'gcloud info'

        - name: 'Set tag sha1 if it does not exist' # the image has not been built because no source has changed
          shell: bash
          run: ''

        - name: 'Create if not exist tag latest to the current sha1 tag' # the image is build for the first time (or tag latest has been removed)
          shell: bash
          run: ''

        - name: 'Allign tag latest if exist to the current sha1 tag' # the image has been build. We translate the tag latest to the new one 
          shell: bash
          run: ''